Update python support to 3.10, 3.11 and 3.12
CQCL/pytket-braket pull request #125
Opened 2024-01-12 13:53 UTC by sjdilkes

This PR drops python 3.9 support and adds python 3.12.

# Checklist

- [ ] I have performed a self-review of my code.
- [ ] I have commented hard-to-understand parts of my code.
- [x] I have made corresponding changes to the public API documentation.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] I have updated the changelog with any user-facing changes.

2024-01-16 16:33 UTC, cqc-alec requested changes
And changelog,..

2024-01-16 16:33 UTC, cqc-alec commented on .github/workflows/build_and_test.yml
Prefer to map (3,9, 3.10, 3.11) --> (3.10, 3.11, 3.12) in this workflow. (So 3.12 will be tested in this PR.)

2024-01-16 16:38 UTC, sjdilkes commented on .github/workflows/build_and_test.yml
I've updated this file to do this mapping

2024-01-16 16:47 UTC, cqc-alec commented
Looks like some dependency requires numpy 1.23.3, which is failing to build on Windows. May have to skip 3.12 tests on Windows for the time being?

2024-01-17 10:24 UTC, sjdilkes commented on README.md
> +`pytket-braket` is available for Python 3.10, 3.11 and 3.12, on Linux, MacOS
added

2024-01-17 10:27 UTC, sjdilkes commented on .github/workflows/build_and_test.yml
> -    - name: Build and test (3.11) - windows
We still should be:
```- name: Build and test including remote checks (3.11) nomypy
      if:  (matrix.os != 'macos-12') && (github.event_name == 'push' || (github.event_name == 'pull_request' &&  github.event.pull_request.head.repo.full_name == github.repository) || github.event_name == 'release' || github.event_name == 'schedule')```
      
I think this is just an artifact of doing the 3.9->3.10, 3.10->3.11, 3.11->3.12 mapping.

2024-01-17 10:32 UTC, cqc-alec approved these changes

2024-01-17 10:44 UTC, merged